import AppBar from '../components/AppBar';
import "../styles/globals.css";

require("@solana/wallet-adapter-react-ui/styles.css");

export const metadata = {
  title: 'BUILDERZ Solana dApp Scaffold',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }: any) {


  return (
    <html lang="en">
      <body>
        <AppBar />
        <main className='min-h-screen'>
          {children}
        </main>
      </body>
    </html>
  );
}
