import { Toaster } from 'sonner';
import "../styles/globals.css";
import AppBar from '../components/layout/AppBar';
import Footer from '../components/layout/Footer';

require("@solana/wallet-adapter-react-ui/styles.css");

export const metadata = {
  title: 'BUILDERZ Solana dApp Scaffold',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }: any) {


  return (
    <html lang="en">
      <body>
        <AppBar />
        <main className='min-h-screen'>
          {children}
        </main>
        <Footer />
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
